### ISSUE TITLE
bc package

### ISSUE THREAD

**Issue by tpimh** [tpimh/nenuzhnix#44]

**Comment by nee-san** [comment]
https://github.com/JanusLinux/janus/blob/pkgutils/packages/bc/Pkgfile

**Comment by lm8** [comment]
Was wondering if you've looked at this implementation:
https://github.com/gavinhoward/bc

**Comment by tpimh** [comment]
Yes, this is exactly what I was thinking about. Also with JanusLinux being renamed the link above would be the following: https://github.com/ataraxialinux/ataraxia/blob/master/packages/bc/KagamiBuild
It's pretty easy to translate KagamiBuild to nenuzhnix rules.
