### ISSUE TITLE
Ninja + stderr = ♥

### ISSUE THREAD

**Issue by dendy** [tpimh/nenuzhnix#54]
Sorry for polluting your project with the unrelated topic, unfortunately there is no messaging feature on the github.

I would push for this issue: https://github.com/ninja-build/ninja/issues/1537
Do you want to contribute in discussion?
Do you by any chance have an access to reopen this issue as an original author?

Thanks in advance!

**Comment by dendy** [comment]
Wonderful, now this message appeared in that thread (-: Conspiracy revealed!

**Comment by tpimh** [comment]
Issue reopened. Also, I would like to add ninja with your patch to my distro, so I wouldn't need that workaround anymore.

**Comment by dendy** [comment]
Thanks! I hope that will bring more attention to this long lasting problem.

**Comment by dendy** [comment]
Спасибо за поддержку (-:
